config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :amazon_api, only: [:index]

  resources :products do
    resources :reviews, only: [:create, :new]
    collection do
      get 'about'
      get 'aboutme'
      get 'myprojects'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :url, presence: true
  validates :price_in_dollar, numericality: {only_integer: true}
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  validates :username, presence: true
  validates :comment, presence: true
  validates :product_id, presence: true
  belongs_to :product
end

app/controllers/amazon_api_controller.rb
class AmazonApiController < ApplicationController


  def index

  end

# private

  # def search_by_keyword(keywords)
    # params = {
    #   "Service" => "AWSECommerceService",
    #   "Operation" => "ItemSearch",
    #   "AWSAccessKeyId" => ACCESS_KEY_ID,
    #   "AssociateTag" => "leavyourrevie-20",
    #   "SearchIndex" => "All",
    #   "Keywords" => keywords,
    #   "ResponseGroup" => "Images,ItemAttributes,Offers"
    # }
    # return params

  # end


  # def request_url(params)
  #   # Set current timestamp if not set
  #   params["Timestamp"] = Time.now.gmtime.iso8601 if !params.key?("Timestamp")
  #
  #   # Generate the canonical query
  #   canonical_query_string = params.sort.collect do |key, value|
  #     [URI.escape(key.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")), URI.escape(value.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))].join('=')
  #   end.join('&')
  #
  #   # Generate the string to be signed
  #   string_to_sign = "GET\n#{ENDPOINT}\n#{REQUEST_URI}\n#{canonical_query_string}"
  #
  #   # Generate the signature required by the Product Advertising API
  #   signature = Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest.new('sha256'), SECRET_KEY, string_to_sign)).strip()
  #
  #   # Generate the signed URL
  #   request_url = "http://#{ENDPOINT}#{REQUEST_URI}?#{canonical_query_string}&Signature=#{URI.escape(signature, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))}"
  #
  #   puts "Signed URL: \"#{request_url}\""
  #
  #   response = HTTParty.get(request_url)
  #
  #
  #   @item_hash = response["ItemSearchResponse"]["Items"]["Item"]
  #
  #   return @item_hash
  #
  #   puts @item_hash
  #
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  attr_accessor :name, :url, :description, :price_in_dollar
  ENDPOINT = "webservices.amazon.com"
  REQUEST_URI = "/onca/xml"
  ACCESS_KEY_ID = ENV["ACCESS_KEY_ID"]
  SECRET_KEY = ENV["SECRET_KEY"]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = @product.reviews.new
    # @review=Review.new
    keywords = @product.name

    params = {
      "Service" => "AWSECommerceService",
      "Operation" => "ItemSearch",
      "AWSAccessKeyId" => ACCESS_KEY_ID,
      "AssociateTag" => "leavyourrevie-20",
      "SearchIndex" => "All",
      "Keywords" => keywords,
      "ResponseGroup" => "Images,ItemAttributes,Offers"
    }

    # Set current timestamp if not set
    params["Timestamp"] = Time.now.gmtime.iso8601 if !params.key?("Timestamp")

    # Generate the canonical query
    canonical_query_string = params.sort.collect do |key, value|
      [URI.escape(key.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")), URI.escape(value.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))].join('=')
    end.join('&')

    # Generate the string to be signed
    string_to_sign = "GET\n#{ENDPOINT}\n#{REQUEST_URI}\n#{canonical_query_string}"

    # Generate the signature required by the Product Advertising API
    signature = Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest.new('sha256'), SECRET_KEY, string_to_sign)).strip()

    # Generate the signed URL
    request_url = "http://#{ENDPOINT}#{REQUEST_URI}?#{canonical_query_string}&Signature=#{URI.escape(signature, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))}"

    puts "Signed URL: \"#{request_url}\""

    response = HTTParty.get(request_url)


    @item_hash = response["ItemSearchResponse"]["Items"]["Item"]

    # keywords = params[:keyword]
    # params = search_by_keyword("Blue Snowball Microphone")
    # @item_hash = request_url(params)

    @amazon_array = []
    @amazon_hash = {}
    @item_hash.map do |item|
      # new_hash["ASIN"]=item["ASIN"]
      puts item["LargeImage"].to_h["URL"]
      @amazon_hash["img_url"] = item["LargeImage"].to_h["URL"]
      puts item["ItemAttributes"]["Brand"]
      @amazon_hash["brand"] = item["ItemAttributes"]["Brand"]
      puts item["ItemAttributes"]["Title"]
      @amazon_hash["description"]=item["ItemAttributes"]["Title"]
      puts item["OfferSummary"]["LowestNewPrice"].to_h["FormattedPrice"]
      @amazon_hash["price"]=item["OfferSummary"]["LowestNewPrice"].to_h["FormattedPrice"]
      puts item["DetailPageURL"]
      @amazon_hash["url"]=item["DetailPageURL"]
      puts item["ASIN"]
      @amazon_hash["id"]=item["ASIN"]
      @amazon_array.push(@amazon_hash)
      @amazon_hash = {}
      puts "======================="
    end
    puts @amazon_array.inspect


    puts "?????"
    puts "?????"

  end

  def new
    @product = Product.new
  end
  def create
    @product = Product.new(product_params)

    flash[:note] = "Your have successfully created a product."
    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    @product.assign_attributes(product_params)

    if @product.save
      redirect_to product_path
    else
      render :edit
    end
  end
  def destroey

  end

  private

  def product_params
    params.require(:product).permit(:name, :url, :description, :price_in_dollar)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  attr_accessor :username, :comment

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new

  end
  def create
    # @review = Product.review.find(params[:product_id])
    puts "what ?"
    # @review = Review.new

    @product = Product.find(params[:product_id])
    puts "what ?"
    @review = @product.reviews.new(review_params)
    # @review = @product.reviews.new
    # @review.username = params[:review][:username]
    # @review.comment = params[:review][:comment]
    # @review.assign_attributess(review_params)
    @review.save

    if @review.save
      flash[:notice] = "sucessfully!"
      redirect_to product_url(@product)
    else
      flash.now[:error] = 'Sorry, try again!'
      render :review
      puts "what ?"
    end

  end

  private

  def review_params
    params.require(:review).permit(:username, :comment)
  end
end

app/helpers/amazon_api_helper.rb
module AmazonApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/amazon_api/_amazon_list.html.erb
<ul class="list-unstyled">
  <% @amazon_array.map do |item|%>
    <li class="media">
      <%=link_to(image_tag("#{item["img_url"]}", size: "250"), "#{item["url"]}", class: "mr-3")%>
      <div class="media-body">
        <h5 class="mt-0 mb-1"><%=item["brand"]%></h5><br>
        <%=item["description"]%><br>
        <%=item["price"]%>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeaveYourReviews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/6bf9c1cbb1.js"></script>
  </head>

  <body>
  <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <h4 class="navbar-brand">Leave Your Reveiws</h4>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%=link_to "Home", root_path, class: "nav-link"%>
        <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%=link_to "New Product", new_product_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=link_to "About the Website", about_products_path, class: "nav-link" %>
      </li>
    </ul>
    <span class="navbar-text">
      <%=link_to "My Projects", myprojects_products_path, class: "nav-link"%>
    </span>
    <span class="navbar-text">
      <%=link_to "About Me", aboutme_products_path, class: "nav-link"%>
    </span>
  </div>
  </nav>
  <%= yield %>
<footer class="footer">
  <div class="container">
    &copy; Leave your reviews by Gina Son
  </div>
</footer>

  </body>
</html>

app/views/products/_all_lists.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row" id="product-list">
      <% @products.each do |product| %>
      <div class="card index list">
        <%=link_to(image_tag("#{product.url}", size: "280", class: "all-list-img"), product_path(product))%>
        <h5><%=product.name%></h5>
        <h5><span class="badge badge-pill badge-warning">$<%=product.price_in_dollar%></span></h5>

      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/about.html.erb
  <div class="jumbotron">
    <h1 class="display-e">Leave your reviews</h1>
    <p class="lead">Leave Your Reviews is a app which allows you to post a product and share your reviews for the product. Once you post your product, you will see other similar products from the Amazon website. As well you are able to leave your reviews for all the products in the app.
    Let’s try!
    </p>
    <hr class="my-4">
    <p>Web Application Framwork: Ruby on Rails</p><br>
    <p>Skills: HTML5, CSS, PostgreSQL, Bootstrap</p><br>
    <p>Web API: Amazon Product Advertising API</p>
    <%=link_to "Try it", new_product_path, class: "btn btn-primary btn-lg"%>
  </div>

app/views/products/aboutme.html.erb
<div class="container">
  <div class="text-center">
    <%=image_tag("gina-profile.jpg", class: "rounded")%>
  <h2 class="myname">Gina Son</h2>
  <h4 class="mytitle">Full Stack Web Developer</h2>
  <div class="social-media">
  <ul class="list-inline">
    <li class="list-inline-item">
      <a href="https://www.linkedin.com/in/gina-son-7268b8ba/" class="fa fa-linkedin" target="_blank"></a>
    </li>
    <li class="list-inline-item">
      <a target="_blank" href="https://github.com/ginason" class="fa fa-github"></a>
    </li>
    <li class="list-inline-item">
      <a target="_blank" class="fa fa-youtube-play" href="https://www.youtube.com/channel/UCIR_ZDOJv-a0rH3qE32CYTg?view_as=subscriber"></a>
    </li>
    <li class="list-inline-item">
      <a class="fa fa-envelope" href="mailto:gina33son@gmail.com"></a>
    </li>
    <li class="list-inline-item">
      <a href="http://www.ginason.me/" class="fa fa-globe" target="_blank"></a>
    </li>
  </ul>
</div>
</div>
</div>

app/views/products/index.html.erb
<section id="home" class="jumnotron text-center">
  <div class="container">
    <h1>Leave Your Reviews</h1>
  </div>
</section>

<%=render "all_lists"%>

app/views/products/myprojects.html.erb
<div class="container">
  <div class="row">
    <div class="card mb-3">
      <%=image_tag("meetmiddle.png", class: "card-img-top")%>
      <div class="card-body">
        <h4 class="card-title">Meet in the Middle</h4>
        <p>This is the app where you can find middle point between you and your friends using Google Maps API. In the middle point you can fine some activities from Yelp API.</p>
        <p class="card-text"><%=link_to "Check it out", "http://www.middlemeet.co", target: "_blank"%></p>
      </div>
    </div>

  <div class="card mb-3">
    <%=image_tag("mathwhatever.png", class: "card-img-top")%>
    <div class="card-body">
      <h4 class="card-title">Mathwhatever</h4>
      <p class="card-text">This is my YouTube channel which is sharing and teaching for Mathematics.</p>
      <p class="card-text"><%=link_to "Check it out", "https://www.youtube.com/channel/UCIR_ZDOJv-a0rH3qE32CYTg?view_as=subscriber", target: "_blank"%> </p>
    </div>
  </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <%= form_for @product, :html => {:class => "form-signin"} do |f|%>
    <h2 class="form-signin-heading">New Product</h2>
    <%= f.label :name, "Product Name" , class: "form-control-label"%>
    <%=f.text_field :name, class: "form-control", placeholder: "Enter proudct name"%>

    <%= f.label :url, "Product image URL", class: "form-control-label"%>
    <%=f.text_field :url, class: "form-control", placeholder: "Enter product url"%>

    <%= f.label :description, "Description", class: "form-control-label"%>
    <%=f.text_area :description, class: "form-control", placeholder: "Enter product's description"%>

    <%= f.label :price_in_dollar, "Price", class: "form-control-label"%>
    <div class="input-group">
    <span class="input-group-addon">$</span>
    <%=f.text_field :price_in_dollar, class: "form-control", placeholder: "Enter product's price"%>
    </div>

    <%=f.submit "Submit", class:"btn btn-secondary", id: "new-product"%>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container">
<section id="item">
  <div class="media item">
    <%=image_tag("#{@product.url}", size: "280", class: "align-self-center mr-3")%><br>
    <div class="media-body">
    <h5 class="mt-0"><%=@product.name%></h5><br>
    <span class="badge badge-pill badge-info">Info</span><br>
    <%=@product.description%><br>
    <span class="badge badge-pill badge-warning">$<%=@product.price_in_dollar%><br></span>
    </div>
  </div>
</section>

<section id="amazon-prodcuts">
  <h1 class="title-amazon">Amazon products related to this item</h1>
  <ul class="list-unstyled">
    <% @amazon_array.map do |item|%>
      <li class="media amazon">
        <%=link_to(image_tag("#{item["img_url"]}", size: "200", class: "mr-3"), "#{item["url"]}", target: "_blank")%>
        <div class="media-body">
          <h5 class="mt-0 mb-1"><%=item["brand"]%></h5><br>
          <%=item["description"]%><br>
          <p><span class="badge badge-pill badge-warning"><%=item["price"]%></span></p>
          <span class="badge badge-success"><%=link_to("Go to Amazon Website", "#{item["url"]}", target: "_blank", class: "amazon-badge")%></span>
        </div>
      </li>
    <% end %>
  </ul>
</section>


<section id="reviews">
  <h1 class="review-font">Reviews</h1>
  <% @product.reviews.each do |review|%>
  <div class="card review">
    <div class="card-header">
      <%=review.username%><br>
    </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p><%=review.comment%><br></p>
        </blockquote>
      </div>
  </div>
  <%end%>

</section>

<section id="new-review">
  <h1 class="new-review-font">Leave a Review</h1>
  <%=render "reviews/form"%>
</section>

</div>

app/views/reviews/_form.html.erb
<div class="container">
    <%= form_for ([@product, @review]) do |f|%>

      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

    <%= f.hidden_field :product_id, value: @product.id%>

    </div>
    <div class="form-group">
      <%=f.label :username, "Username"%>
      <%=f.text_field :username, class: "form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :comment, "Comment"%>
      <%=f.text_area :comment, placeholder: "Leave your comment!", class: "form-control"%>
    </div>
    <%=f.submit "Submit!", class: "btn btn-secondary"%>
    <%end%>
</div>

app/views/reviews/_new.html.erb
<h1>save??</h1>
<h1>Comments!!</h1>

<% @product.reviews.each do |review|%>
<%=review.username%><br>
<%=review.comment%><br>
<%=review.product_id%>
<%end%>

app/views/reviews/review.html.erb
<%=render "form"%>